import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bienvenidos a mi Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenidos a <Link href='/postdetalle'>MiBlog</Link>
        </h1>

        <h2 className={styles.description}>
          Blog Personal
        </h2>

        <div className={styles.grid}>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://alexis19b.github.io/landingpage/Portafolio/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Elaborador por Jesus Briceño 2021
        </a>
      </footer>
    </div>
  )
}
